- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Started and service nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create a html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: download the artifact
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: Extracting the web artifact
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy roboshop.conf file to default.d
  ansible.builtin.templete:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf 
 
- name: restart nginx
  ansible.builtin.services:
    name: nginx
    state: restarted